export TERRAGOAT_RESOURCE_GROUP="RG_TP_Azure_Hardening"
export TERRAGOAT_STATE_CONTAINER="mydevsecops"
export TERRAGOAT_STATE_STORAGE_ACCOUNT="terragoatmodsa"
export TF_VAR_environment="dev"
export TF_VAR_region="francecentral"
